services:
  api:
    build: .  # <--- Esto le dice: "Usa el Dockerfile de esta carpeta"
    volumes:
      - .:/app
    ports:
      - "8000:80"
    extra_hosts:
      - "host.docker.internal:host-gateway"